#!/bin/bash

#get playing state from statefile, mpd might not be started
state=$(grep "^state\:" /persist/mpd/state | awk '{print $2}')

# restore playing state at end of script
function cleanup {
  mpc "$state"
}
trap cleanup EXIT

[ -d /media/usb ] && rmdir /media/usb

# wait until mpd is started
until pidof mpd
do
  sleep 0.5
done

# update the mpd library
/usr/bin/mpc update --wait > /dev/null

playlist=$(mpc playlist -f %file%)

# if playlist is empty add all files in /media
if [ -z "$playlist" ]; then
  mpc add media
  exit 0
fi

# add files not in playlist
while IFS= read -r -d '' folder
do
  myfolder=$(echo "$folder" | cut -c 2-)
  match=$(echo "$playlist" | grep "$myfolder")
  if [ -z "$match" ]; then
    myfolder=$(echo "$folder" | cut -c 2-)
    echo "adding $myfolder"
    mpc add "$myfolder"
    playlist=$(mpc playlist -f %file%)
  fi
done <  <(find /media/ -mindepth 2 -type d -not -path "*/\.*" -print0)
